/*
 * This source file was generated by the Gradle 'init' task
 */
package com.gix.rust_native

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    // native interface

    external fun helloFromRust(name: String): String

    companion object{
        init{
            System.loadLibrary("test_rust")
        }
    }
}
