/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

application {
    // Define the main class for the application.
    mainClass = "com.gix.rust_native.MainKt"

    var debug="debug"
    if(System.getProperty("Debug","false")=="true"){
        debug="release"
    }

    applicationDefaultJvmArgs += listOf(
        "-Djava.library.path=${rootProject.projectDir}/native_rust/target/${debug}"
    )


}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()

    var debug="debug"
    if(System.getProperty("Debug","false")=="true"){
        debug="release"
    }

    systemProperty(
        "java.library.path",
        "${rootProject.projectDir}/native_rust/target/${debug}"//Replace : with ; for windows
    )

}

tasks["run"].dependsOn(":native_rust:buildRust")
tasks["build"].dependsOn(":native_rust:buildRust")
tasks["test"].dependsOn(":native_rust:buildRust")
tasks["clean"].dependsOn(":native_rust:clean")
